/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as NoauthImport } from './routes/_no_auth'
import { Route as AuthImport } from './routes/_auth'
import { Route as AuthUserImport } from './routes/_auth/_user'
import { Route as AuthAdminImport } from './routes/_auth/_admin'
import { Route as AuthUserUserTaskListIndexImport } from './routes/_auth/_user/user-task-list/index'
import { Route as AuthUserOrderListIndexImport } from './routes/_auth/_user/order-list/index'
import { Route as AuthUserInfoIndexImport } from './routes/_auth/_user/info/index'
import { Route as AuthAdminUserListIndexImport } from './routes/_auth/_admin/user-list/index'
import { Route as AuthAdminTaskListIndexImport } from './routes/_auth/_admin/task-list/index'
import { Route as AuthAdminOrdersIndexImport } from './routes/_auth/_admin/orders/index'

// Create Virtual Routes

const NotfoundIndexLazyImport = createFileRoute('/not_found/')()
const AuthIndexLazyImport = createFileRoute('/_auth/')()
const NoauthAuthSignUpIndexLazyImport = createFileRoute(
  '/_no_auth/auth/sign-up/',
)()
const NoauthAuthSignInIndexLazyImport = createFileRoute(
  '/_no_auth/auth/sign-in/',
)()
const NoauthAuthConfirmEmailIndexLazyImport = createFileRoute(
  '/_no_auth/auth/confirm-email/',
)()

// Create/Update Routes

const NoauthRoute = NoauthImport.update({
  id: '/_no_auth',
  getParentRoute: () => rootRoute,
} as any)

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const NotfoundIndexLazyRoute = NotfoundIndexLazyImport.update({
  id: '/not_found/',
  path: '/not_found/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/not_found/index.lazy').then((d) => d.Route),
)

const AuthIndexLazyRoute = AuthIndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any).lazy(() => import('./routes/_auth/index.lazy').then((d) => d.Route))

const AuthUserRoute = AuthUserImport.update({
  id: '/_user',
  getParentRoute: () => AuthRoute,
} as any)

const AuthAdminRoute = AuthAdminImport.update({
  id: '/_admin',
  getParentRoute: () => AuthRoute,
} as any)

const NoauthAuthSignUpIndexLazyRoute = NoauthAuthSignUpIndexLazyImport.update({
  id: '/auth/sign-up/',
  path: '/auth/sign-up/',
  getParentRoute: () => NoauthRoute,
} as any).lazy(() =>
  import('./routes/_no_auth/auth/sign-up/index.lazy').then((d) => d.Route),
)

const NoauthAuthSignInIndexLazyRoute = NoauthAuthSignInIndexLazyImport.update({
  id: '/auth/sign-in/',
  path: '/auth/sign-in/',
  getParentRoute: () => NoauthRoute,
} as any).lazy(() =>
  import('./routes/_no_auth/auth/sign-in/index.lazy').then((d) => d.Route),
)

const NoauthAuthConfirmEmailIndexLazyRoute =
  NoauthAuthConfirmEmailIndexLazyImport.update({
    id: '/auth/confirm-email/',
    path: '/auth/confirm-email/',
    getParentRoute: () => NoauthRoute,
  } as any).lazy(() =>
    import('./routes/_no_auth/auth/confirm-email/index.lazy').then(
      (d) => d.Route,
    ),
  )

const AuthUserUserTaskListIndexRoute = AuthUserUserTaskListIndexImport.update({
  id: '/user-task-list/',
  path: '/user-task-list/',
  getParentRoute: () => AuthUserRoute,
} as any)

const AuthUserOrderListIndexRoute = AuthUserOrderListIndexImport.update({
  id: '/order-list/',
  path: '/order-list/',
  getParentRoute: () => AuthUserRoute,
} as any)

const AuthUserInfoIndexRoute = AuthUserInfoIndexImport.update({
  id: '/info/',
  path: '/info/',
  getParentRoute: () => AuthUserRoute,
} as any)

const AuthAdminUserListIndexRoute = AuthAdminUserListIndexImport.update({
  id: '/user-list/',
  path: '/user-list/',
  getParentRoute: () => AuthAdminRoute,
} as any)

const AuthAdminTaskListIndexRoute = AuthAdminTaskListIndexImport.update({
  id: '/task-list/',
  path: '/task-list/',
  getParentRoute: () => AuthAdminRoute,
} as any)

const AuthAdminOrdersIndexRoute = AuthAdminOrdersIndexImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => AuthAdminRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/_no_auth': {
      id: '/_no_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof NoauthImport
      parentRoute: typeof rootRoute
    }
    '/_auth/_admin': {
      id: '/_auth/_admin'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthAdminImport
      parentRoute: typeof AuthImport
    }
    '/_auth/_user': {
      id: '/_auth/_user'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthUserImport
      parentRoute: typeof AuthImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexLazyImport
      parentRoute: typeof AuthImport
    }
    '/not_found/': {
      id: '/not_found/'
      path: '/not_found'
      fullPath: '/not_found'
      preLoaderRoute: typeof NotfoundIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/_auth/_admin/orders/': {
      id: '/_auth/_admin/orders/'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AuthAdminOrdersIndexImport
      parentRoute: typeof AuthAdminImport
    }
    '/_auth/_admin/task-list/': {
      id: '/_auth/_admin/task-list/'
      path: '/task-list'
      fullPath: '/task-list'
      preLoaderRoute: typeof AuthAdminTaskListIndexImport
      parentRoute: typeof AuthAdminImport
    }
    '/_auth/_admin/user-list/': {
      id: '/_auth/_admin/user-list/'
      path: '/user-list'
      fullPath: '/user-list'
      preLoaderRoute: typeof AuthAdminUserListIndexImport
      parentRoute: typeof AuthAdminImport
    }
    '/_auth/_user/info/': {
      id: '/_auth/_user/info/'
      path: '/info'
      fullPath: '/info'
      preLoaderRoute: typeof AuthUserInfoIndexImport
      parentRoute: typeof AuthUserImport
    }
    '/_auth/_user/order-list/': {
      id: '/_auth/_user/order-list/'
      path: '/order-list'
      fullPath: '/order-list'
      preLoaderRoute: typeof AuthUserOrderListIndexImport
      parentRoute: typeof AuthUserImport
    }
    '/_auth/_user/user-task-list/': {
      id: '/_auth/_user/user-task-list/'
      path: '/user-task-list'
      fullPath: '/user-task-list'
      preLoaderRoute: typeof AuthUserUserTaskListIndexImport
      parentRoute: typeof AuthUserImport
    }
    '/_no_auth/auth/confirm-email/': {
      id: '/_no_auth/auth/confirm-email/'
      path: '/auth/confirm-email'
      fullPath: '/auth/confirm-email'
      preLoaderRoute: typeof NoauthAuthConfirmEmailIndexLazyImport
      parentRoute: typeof NoauthImport
    }
    '/_no_auth/auth/sign-in/': {
      id: '/_no_auth/auth/sign-in/'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof NoauthAuthSignInIndexLazyImport
      parentRoute: typeof NoauthImport
    }
    '/_no_auth/auth/sign-up/': {
      id: '/_no_auth/auth/sign-up/'
      path: '/auth/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof NoauthAuthSignUpIndexLazyImport
      parentRoute: typeof NoauthImport
    }
  }
}

// Create and export the route tree

interface AuthAdminRouteChildren {
  AuthAdminOrdersIndexRoute: typeof AuthAdminOrdersIndexRoute
  AuthAdminTaskListIndexRoute: typeof AuthAdminTaskListIndexRoute
  AuthAdminUserListIndexRoute: typeof AuthAdminUserListIndexRoute
}

const AuthAdminRouteChildren: AuthAdminRouteChildren = {
  AuthAdminOrdersIndexRoute: AuthAdminOrdersIndexRoute,
  AuthAdminTaskListIndexRoute: AuthAdminTaskListIndexRoute,
  AuthAdminUserListIndexRoute: AuthAdminUserListIndexRoute,
}

const AuthAdminRouteWithChildren = AuthAdminRoute._addFileChildren(
  AuthAdminRouteChildren,
)

interface AuthUserRouteChildren {
  AuthUserInfoIndexRoute: typeof AuthUserInfoIndexRoute
  AuthUserOrderListIndexRoute: typeof AuthUserOrderListIndexRoute
  AuthUserUserTaskListIndexRoute: typeof AuthUserUserTaskListIndexRoute
}

const AuthUserRouteChildren: AuthUserRouteChildren = {
  AuthUserInfoIndexRoute: AuthUserInfoIndexRoute,
  AuthUserOrderListIndexRoute: AuthUserOrderListIndexRoute,
  AuthUserUserTaskListIndexRoute: AuthUserUserTaskListIndexRoute,
}

const AuthUserRouteWithChildren = AuthUserRoute._addFileChildren(
  AuthUserRouteChildren,
)

interface AuthRouteChildren {
  AuthAdminRoute: typeof AuthAdminRouteWithChildren
  AuthUserRoute: typeof AuthUserRouteWithChildren
  AuthIndexLazyRoute: typeof AuthIndexLazyRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAdminRoute: AuthAdminRouteWithChildren,
  AuthUserRoute: AuthUserRouteWithChildren,
  AuthIndexLazyRoute: AuthIndexLazyRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface NoauthRouteChildren {
  NoauthAuthConfirmEmailIndexLazyRoute: typeof NoauthAuthConfirmEmailIndexLazyRoute
  NoauthAuthSignInIndexLazyRoute: typeof NoauthAuthSignInIndexLazyRoute
  NoauthAuthSignUpIndexLazyRoute: typeof NoauthAuthSignUpIndexLazyRoute
}

const NoauthRouteChildren: NoauthRouteChildren = {
  NoauthAuthConfirmEmailIndexLazyRoute: NoauthAuthConfirmEmailIndexLazyRoute,
  NoauthAuthSignInIndexLazyRoute: NoauthAuthSignInIndexLazyRoute,
  NoauthAuthSignUpIndexLazyRoute: NoauthAuthSignUpIndexLazyRoute,
}

const NoauthRouteWithChildren =
  NoauthRoute._addFileChildren(NoauthRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof AuthUserRouteWithChildren
  '/': typeof AuthIndexLazyRoute
  '/not_found': typeof NotfoundIndexLazyRoute
  '/orders': typeof AuthAdminOrdersIndexRoute
  '/task-list': typeof AuthAdminTaskListIndexRoute
  '/user-list': typeof AuthAdminUserListIndexRoute
  '/info': typeof AuthUserInfoIndexRoute
  '/order-list': typeof AuthUserOrderListIndexRoute
  '/user-task-list': typeof AuthUserUserTaskListIndexRoute
  '/auth/confirm-email': typeof NoauthAuthConfirmEmailIndexLazyRoute
  '/auth/sign-in': typeof NoauthAuthSignInIndexLazyRoute
  '/auth/sign-up': typeof NoauthAuthSignUpIndexLazyRoute
}

export interface FileRoutesByTo {
  '': typeof AuthUserRouteWithChildren
  '/': typeof AuthIndexLazyRoute
  '/not_found': typeof NotfoundIndexLazyRoute
  '/orders': typeof AuthAdminOrdersIndexRoute
  '/task-list': typeof AuthAdminTaskListIndexRoute
  '/user-list': typeof AuthAdminUserListIndexRoute
  '/info': typeof AuthUserInfoIndexRoute
  '/order-list': typeof AuthUserOrderListIndexRoute
  '/user-task-list': typeof AuthUserUserTaskListIndexRoute
  '/auth/confirm-email': typeof NoauthAuthConfirmEmailIndexLazyRoute
  '/auth/sign-in': typeof NoauthAuthSignInIndexLazyRoute
  '/auth/sign-up': typeof NoauthAuthSignUpIndexLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_no_auth': typeof NoauthRouteWithChildren
  '/_auth/_admin': typeof AuthAdminRouteWithChildren
  '/_auth/_user': typeof AuthUserRouteWithChildren
  '/_auth/': typeof AuthIndexLazyRoute
  '/not_found/': typeof NotfoundIndexLazyRoute
  '/_auth/_admin/orders/': typeof AuthAdminOrdersIndexRoute
  '/_auth/_admin/task-list/': typeof AuthAdminTaskListIndexRoute
  '/_auth/_admin/user-list/': typeof AuthAdminUserListIndexRoute
  '/_auth/_user/info/': typeof AuthUserInfoIndexRoute
  '/_auth/_user/order-list/': typeof AuthUserOrderListIndexRoute
  '/_auth/_user/user-task-list/': typeof AuthUserUserTaskListIndexRoute
  '/_no_auth/auth/confirm-email/': typeof NoauthAuthConfirmEmailIndexLazyRoute
  '/_no_auth/auth/sign-in/': typeof NoauthAuthSignInIndexLazyRoute
  '/_no_auth/auth/sign-up/': typeof NoauthAuthSignUpIndexLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/'
    | '/not_found'
    | '/orders'
    | '/task-list'
    | '/user-list'
    | '/info'
    | '/order-list'
    | '/user-task-list'
    | '/auth/confirm-email'
    | '/auth/sign-in'
    | '/auth/sign-up'
  fileRoutesByTo: FileRoutesByTo
  to:
    | ''
    | '/'
    | '/not_found'
    | '/orders'
    | '/task-list'
    | '/user-list'
    | '/info'
    | '/order-list'
    | '/user-task-list'
    | '/auth/confirm-email'
    | '/auth/sign-in'
    | '/auth/sign-up'
  id:
    | '__root__'
    | '/_auth'
    | '/_no_auth'
    | '/_auth/_admin'
    | '/_auth/_user'
    | '/_auth/'
    | '/not_found/'
    | '/_auth/_admin/orders/'
    | '/_auth/_admin/task-list/'
    | '/_auth/_admin/user-list/'
    | '/_auth/_user/info/'
    | '/_auth/_user/order-list/'
    | '/_auth/_user/user-task-list/'
    | '/_no_auth/auth/confirm-email/'
    | '/_no_auth/auth/sign-in/'
    | '/_no_auth/auth/sign-up/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  NoauthRoute: typeof NoauthRouteWithChildren
  NotfoundIndexLazyRoute: typeof NotfoundIndexLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  NoauthRoute: NoauthRouteWithChildren,
  NotfoundIndexLazyRoute: NotfoundIndexLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_auth",
        "/_no_auth",
        "/not_found/"
      ]
    },
    "/_auth": {
      "filePath": "_auth.tsx",
      "children": [
        "/_auth/_admin",
        "/_auth/_user",
        "/_auth/"
      ]
    },
    "/_no_auth": {
      "filePath": "_no_auth.tsx",
      "children": [
        "/_no_auth/auth/confirm-email/",
        "/_no_auth/auth/sign-in/",
        "/_no_auth/auth/sign-up/"
      ]
    },
    "/_auth/_admin": {
      "filePath": "_auth/_admin.tsx",
      "parent": "/_auth",
      "children": [
        "/_auth/_admin/orders/",
        "/_auth/_admin/task-list/",
        "/_auth/_admin/user-list/"
      ]
    },
    "/_auth/_user": {
      "filePath": "_auth/_user.tsx",
      "parent": "/_auth",
      "children": [
        "/_auth/_user/info/",
        "/_auth/_user/order-list/",
        "/_auth/_user/user-task-list/"
      ]
    },
    "/_auth/": {
      "filePath": "_auth/index.lazy.tsx",
      "parent": "/_auth"
    },
    "/not_found/": {
      "filePath": "not_found/index.lazy.tsx"
    },
    "/_auth/_admin/orders/": {
      "filePath": "_auth/_admin/orders/index.tsx",
      "parent": "/_auth/_admin"
    },
    "/_auth/_admin/task-list/": {
      "filePath": "_auth/_admin/task-list/index.tsx",
      "parent": "/_auth/_admin"
    },
    "/_auth/_admin/user-list/": {
      "filePath": "_auth/_admin/user-list/index.tsx",
      "parent": "/_auth/_admin"
    },
    "/_auth/_user/info/": {
      "filePath": "_auth/_user/info/index.tsx",
      "parent": "/_auth/_user"
    },
    "/_auth/_user/order-list/": {
      "filePath": "_auth/_user/order-list/index.tsx",
      "parent": "/_auth/_user"
    },
    "/_auth/_user/user-task-list/": {
      "filePath": "_auth/_user/user-task-list/index.tsx",
      "parent": "/_auth/_user"
    },
    "/_no_auth/auth/confirm-email/": {
      "filePath": "_no_auth/auth/confirm-email/index.lazy.tsx",
      "parent": "/_no_auth"
    },
    "/_no_auth/auth/sign-in/": {
      "filePath": "_no_auth/auth/sign-in/index.lazy.tsx",
      "parent": "/_no_auth"
    },
    "/_no_auth/auth/sign-up/": {
      "filePath": "_no_auth/auth/sign-up/index.lazy.tsx",
      "parent": "/_no_auth"
    }
  }
}
ROUTE_MANIFEST_END */
