/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as NoauthImport } from './routes/_no_auth'
import { Route as AuthImport } from './routes/_auth'
import { Route as AuthUserImport } from './routes/_auth/_user'
import { Route as AuthAdminImport } from './routes/_auth/_admin'
import { Route as AuthUserWalletIndexImport } from './routes/_auth/_user/wallet/index'
import { Route as AuthUserStepsIndexImport } from './routes/_auth/_user/steps/index'
import { Route as AuthUserPartnerProgramIndexImport } from './routes/_auth/_user/partner-program/index'
import { Route as AuthUserOrdersIndexImport } from './routes/_auth/_user/orders/index'
import { Route as AuthUserMyInformationIndexImport } from './routes/_auth/_user/my-information/index'
import { Route as AuthUserDepositInfoIndexImport } from './routes/_auth/_user/deposit-info/index'
import { Route as AuthAdminWalletListIndexImport } from './routes/_auth/_admin/wallet-list/index'
import { Route as AuthAdminUserListIndexImport } from './routes/_auth/_admin/user-list/index'
import { Route as AuthAdminReportsIndexImport } from './routes/_auth/_admin/reports/index'
import { Route as AuthAdminReferredUsersIndexImport } from './routes/_auth/_admin/referred-users/index'
import { Route as AuthAdminPlatipayIndexImport } from './routes/_auth/_admin/platipay/index'
import { Route as AuthAdminOrderListIndexImport } from './routes/_auth/_admin/order-list/index'
import { Route as AuthAdminDepositListIndexImport } from './routes/_auth/_admin/deposit-list/index'
import { Route as AuthAdminBlockedCardListIndexImport } from './routes/_auth/_admin/blocked-card-list/index'
import { Route as AuthAdminBankCardListIndexImport } from './routes/_auth/_admin/bank-card-list/index'
import { Route as AuthUserOrdersIdImport } from './routes/_auth/_user/orders/$id'
import { Route as AuthUserDepositInfoIdImport } from './routes/_auth/_user/deposit-info/$id'
import { Route as AuthAdminUserListIdImport } from './routes/_auth/_admin/user-list/$id'
import { Route as AuthAdminOrderListIdImport } from './routes/_auth/_admin/order-list/$id'
import { Route as AuthAdminDepositListIdImport } from './routes/_auth/_admin/deposit-list/$id'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()
const NotfoundIndexLazyImport = createFileRoute('/not_found/')()
const NoauthLandingPageIndexLazyImport = createFileRoute(
  '/_no_auth/landing-page/',
)()
const NoauthAuthSignUpIndexLazyImport = createFileRoute(
  '/_no_auth/auth/sign-up/',
)()
const NoauthAuthSignInIndexLazyImport = createFileRoute(
  '/_no_auth/auth/sign-in/',
)()
const NoauthAuthResetPasswordIndexLazyImport = createFileRoute(
  '/_no_auth/auth/reset-password/',
)()
const NoauthAuthConfirmEmailIndexLazyImport = createFileRoute(
  '/_no_auth/auth/confirm-email/',
)()
const NoauthAuthChangePasswordIndexLazyImport = createFileRoute(
  '/_no_auth/auth/change-password/',
)()

// Create/Update Routes

const NoauthRoute = NoauthImport.update({
  id: '/_no_auth',
  getParentRoute: () => rootRoute,
} as any)

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const NotfoundIndexLazyRoute = NotfoundIndexLazyImport.update({
  id: '/not_found/',
  path: '/not_found/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/not_found/index.lazy').then((d) => d.Route),
)

const AuthUserRoute = AuthUserImport.update({
  id: '/_user',
  getParentRoute: () => AuthRoute,
} as any)

const AuthAdminRoute = AuthAdminImport.update({
  id: '/_admin',
  getParentRoute: () => AuthRoute,
} as any)

const NoauthLandingPageIndexLazyRoute = NoauthLandingPageIndexLazyImport.update(
  {
    id: '/landing-page/',
    path: '/landing-page/',
    getParentRoute: () => NoauthRoute,
  } as any,
).lazy(() =>
  import('./routes/_no_auth/landing-page/index.lazy').then((d) => d.Route),
)

const NoauthAuthSignUpIndexLazyRoute = NoauthAuthSignUpIndexLazyImport.update({
  id: '/auth/sign-up/',
  path: '/auth/sign-up/',
  getParentRoute: () => NoauthRoute,
} as any).lazy(() =>
  import('./routes/_no_auth/auth/sign-up/index.lazy').then((d) => d.Route),
)

const NoauthAuthSignInIndexLazyRoute = NoauthAuthSignInIndexLazyImport.update({
  id: '/auth/sign-in/',
  path: '/auth/sign-in/',
  getParentRoute: () => NoauthRoute,
} as any).lazy(() =>
  import('./routes/_no_auth/auth/sign-in/index.lazy').then((d) => d.Route),
)

const NoauthAuthResetPasswordIndexLazyRoute =
  NoauthAuthResetPasswordIndexLazyImport.update({
    id: '/auth/reset-password/',
    path: '/auth/reset-password/',
    getParentRoute: () => NoauthRoute,
  } as any).lazy(() =>
    import('./routes/_no_auth/auth/reset-password/index.lazy').then(
      (d) => d.Route,
    ),
  )

const NoauthAuthConfirmEmailIndexLazyRoute =
  NoauthAuthConfirmEmailIndexLazyImport.update({
    id: '/auth/confirm-email/',
    path: '/auth/confirm-email/',
    getParentRoute: () => NoauthRoute,
  } as any).lazy(() =>
    import('./routes/_no_auth/auth/confirm-email/index.lazy').then(
      (d) => d.Route,
    ),
  )

const NoauthAuthChangePasswordIndexLazyRoute =
  NoauthAuthChangePasswordIndexLazyImport.update({
    id: '/auth/change-password/',
    path: '/auth/change-password/',
    getParentRoute: () => NoauthRoute,
  } as any).lazy(() =>
    import('./routes/_no_auth/auth/change-password/index.lazy').then(
      (d) => d.Route,
    ),
  )

const AuthUserWalletIndexRoute = AuthUserWalletIndexImport.update({
  id: '/wallet/',
  path: '/wallet/',
  getParentRoute: () => AuthUserRoute,
} as any)

const AuthUserStepsIndexRoute = AuthUserStepsIndexImport.update({
  id: '/steps/',
  path: '/steps/',
  getParentRoute: () => AuthUserRoute,
} as any)

const AuthUserPartnerProgramIndexRoute =
  AuthUserPartnerProgramIndexImport.update({
    id: '/partner-program/',
    path: '/partner-program/',
    getParentRoute: () => AuthUserRoute,
  } as any)

const AuthUserOrdersIndexRoute = AuthUserOrdersIndexImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => AuthUserRoute,
} as any)

const AuthUserMyInformationIndexRoute = AuthUserMyInformationIndexImport.update(
  {
    id: '/my-information/',
    path: '/my-information/',
    getParentRoute: () => AuthUserRoute,
  } as any,
)

const AuthUserDepositInfoIndexRoute = AuthUserDepositInfoIndexImport.update({
  id: '/deposit-info/',
  path: '/deposit-info/',
  getParentRoute: () => AuthUserRoute,
} as any)

const AuthAdminWalletListIndexRoute = AuthAdminWalletListIndexImport.update({
  id: '/wallet-list/',
  path: '/wallet-list/',
  getParentRoute: () => AuthAdminRoute,
} as any)

const AuthAdminUserListIndexRoute = AuthAdminUserListIndexImport.update({
  id: '/user-list/',
  path: '/user-list/',
  getParentRoute: () => AuthAdminRoute,
} as any)

const AuthAdminReportsIndexRoute = AuthAdminReportsIndexImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => AuthAdminRoute,
} as any)

const AuthAdminReferredUsersIndexRoute =
  AuthAdminReferredUsersIndexImport.update({
    id: '/referred-users/',
    path: '/referred-users/',
    getParentRoute: () => AuthAdminRoute,
  } as any)

const AuthAdminPlatipayIndexRoute = AuthAdminPlatipayIndexImport.update({
  id: '/platipay/',
  path: '/platipay/',
  getParentRoute: () => AuthAdminRoute,
} as any)

const AuthAdminOrderListIndexRoute = AuthAdminOrderListIndexImport.update({
  id: '/order-list/',
  path: '/order-list/',
  getParentRoute: () => AuthAdminRoute,
} as any)

const AuthAdminDepositListIndexRoute = AuthAdminDepositListIndexImport.update({
  id: '/deposit-list/',
  path: '/deposit-list/',
  getParentRoute: () => AuthAdminRoute,
} as any)

const AuthAdminBlockedCardListIndexRoute =
  AuthAdminBlockedCardListIndexImport.update({
    id: '/blocked-card-list/',
    path: '/blocked-card-list/',
    getParentRoute: () => AuthAdminRoute,
  } as any)

const AuthAdminBankCardListIndexRoute = AuthAdminBankCardListIndexImport.update(
  {
    id: '/bank-card-list/',
    path: '/bank-card-list/',
    getParentRoute: () => AuthAdminRoute,
  } as any,
)

const AuthUserOrdersIdRoute = AuthUserOrdersIdImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => AuthUserRoute,
} as any)

const AuthUserDepositInfoIdRoute = AuthUserDepositInfoIdImport.update({
  id: '/deposit-info/$id',
  path: '/deposit-info/$id',
  getParentRoute: () => AuthUserRoute,
} as any)

const AuthAdminUserListIdRoute = AuthAdminUserListIdImport.update({
  id: '/user-list/$id',
  path: '/user-list/$id',
  getParentRoute: () => AuthAdminRoute,
} as any)

const AuthAdminOrderListIdRoute = AuthAdminOrderListIdImport.update({
  id: '/order-list/$id',
  path: '/order-list/$id',
  getParentRoute: () => AuthAdminRoute,
} as any)

const AuthAdminDepositListIdRoute = AuthAdminDepositListIdImport.update({
  id: '/deposit-list/$id',
  path: '/deposit-list/$id',
  getParentRoute: () => AuthAdminRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/_no_auth': {
      id: '/_no_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof NoauthImport
      parentRoute: typeof rootRoute
    }
    '/_auth/_admin': {
      id: '/_auth/_admin'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthAdminImport
      parentRoute: typeof AuthImport
    }
    '/_auth/_user': {
      id: '/_auth/_user'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthUserImport
      parentRoute: typeof AuthImport
    }
    '/not_found/': {
      id: '/not_found/'
      path: '/not_found'
      fullPath: '/not_found'
      preLoaderRoute: typeof NotfoundIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/_no_auth/landing-page/': {
      id: '/_no_auth/landing-page/'
      path: '/landing-page'
      fullPath: '/landing-page'
      preLoaderRoute: typeof NoauthLandingPageIndexLazyImport
      parentRoute: typeof NoauthImport
    }
    '/_auth/_admin/deposit-list/$id': {
      id: '/_auth/_admin/deposit-list/$id'
      path: '/deposit-list/$id'
      fullPath: '/deposit-list/$id'
      preLoaderRoute: typeof AuthAdminDepositListIdImport
      parentRoute: typeof AuthAdminImport
    }
    '/_auth/_admin/order-list/$id': {
      id: '/_auth/_admin/order-list/$id'
      path: '/order-list/$id'
      fullPath: '/order-list/$id'
      preLoaderRoute: typeof AuthAdminOrderListIdImport
      parentRoute: typeof AuthAdminImport
    }
    '/_auth/_admin/user-list/$id': {
      id: '/_auth/_admin/user-list/$id'
      path: '/user-list/$id'
      fullPath: '/user-list/$id'
      preLoaderRoute: typeof AuthAdminUserListIdImport
      parentRoute: typeof AuthAdminImport
    }
    '/_auth/_user/deposit-info/$id': {
      id: '/_auth/_user/deposit-info/$id'
      path: '/deposit-info/$id'
      fullPath: '/deposit-info/$id'
      preLoaderRoute: typeof AuthUserDepositInfoIdImport
      parentRoute: typeof AuthUserImport
    }
    '/_auth/_user/orders/$id': {
      id: '/_auth/_user/orders/$id'
      path: '/orders/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof AuthUserOrdersIdImport
      parentRoute: typeof AuthUserImport
    }
    '/_auth/_admin/bank-card-list/': {
      id: '/_auth/_admin/bank-card-list/'
      path: '/bank-card-list'
      fullPath: '/bank-card-list'
      preLoaderRoute: typeof AuthAdminBankCardListIndexImport
      parentRoute: typeof AuthAdminImport
    }
    '/_auth/_admin/blocked-card-list/': {
      id: '/_auth/_admin/blocked-card-list/'
      path: '/blocked-card-list'
      fullPath: '/blocked-card-list'
      preLoaderRoute: typeof AuthAdminBlockedCardListIndexImport
      parentRoute: typeof AuthAdminImport
    }
    '/_auth/_admin/deposit-list/': {
      id: '/_auth/_admin/deposit-list/'
      path: '/deposit-list'
      fullPath: '/deposit-list'
      preLoaderRoute: typeof AuthAdminDepositListIndexImport
      parentRoute: typeof AuthAdminImport
    }
    '/_auth/_admin/order-list/': {
      id: '/_auth/_admin/order-list/'
      path: '/order-list'
      fullPath: '/order-list'
      preLoaderRoute: typeof AuthAdminOrderListIndexImport
      parentRoute: typeof AuthAdminImport
    }
    '/_auth/_admin/platipay/': {
      id: '/_auth/_admin/platipay/'
      path: '/platipay'
      fullPath: '/platipay'
      preLoaderRoute: typeof AuthAdminPlatipayIndexImport
      parentRoute: typeof AuthAdminImport
    }
    '/_auth/_admin/referred-users/': {
      id: '/_auth/_admin/referred-users/'
      path: '/referred-users'
      fullPath: '/referred-users'
      preLoaderRoute: typeof AuthAdminReferredUsersIndexImport
      parentRoute: typeof AuthAdminImport
    }
    '/_auth/_admin/reports/': {
      id: '/_auth/_admin/reports/'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthAdminReportsIndexImport
      parentRoute: typeof AuthAdminImport
    }
    '/_auth/_admin/user-list/': {
      id: '/_auth/_admin/user-list/'
      path: '/user-list'
      fullPath: '/user-list'
      preLoaderRoute: typeof AuthAdminUserListIndexImport
      parentRoute: typeof AuthAdminImport
    }
    '/_auth/_admin/wallet-list/': {
      id: '/_auth/_admin/wallet-list/'
      path: '/wallet-list'
      fullPath: '/wallet-list'
      preLoaderRoute: typeof AuthAdminWalletListIndexImport
      parentRoute: typeof AuthAdminImport
    }
    '/_auth/_user/deposit-info/': {
      id: '/_auth/_user/deposit-info/'
      path: '/deposit-info'
      fullPath: '/deposit-info'
      preLoaderRoute: typeof AuthUserDepositInfoIndexImport
      parentRoute: typeof AuthUserImport
    }
    '/_auth/_user/my-information/': {
      id: '/_auth/_user/my-information/'
      path: '/my-information'
      fullPath: '/my-information'
      preLoaderRoute: typeof AuthUserMyInformationIndexImport
      parentRoute: typeof AuthUserImport
    }
    '/_auth/_user/orders/': {
      id: '/_auth/_user/orders/'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AuthUserOrdersIndexImport
      parentRoute: typeof AuthUserImport
    }
    '/_auth/_user/partner-program/': {
      id: '/_auth/_user/partner-program/'
      path: '/partner-program'
      fullPath: '/partner-program'
      preLoaderRoute: typeof AuthUserPartnerProgramIndexImport
      parentRoute: typeof AuthUserImport
    }
    '/_auth/_user/steps/': {
      id: '/_auth/_user/steps/'
      path: '/steps'
      fullPath: '/steps'
      preLoaderRoute: typeof AuthUserStepsIndexImport
      parentRoute: typeof AuthUserImport
    }
    '/_auth/_user/wallet/': {
      id: '/_auth/_user/wallet/'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof AuthUserWalletIndexImport
      parentRoute: typeof AuthUserImport
    }
    '/_no_auth/auth/change-password/': {
      id: '/_no_auth/auth/change-password/'
      path: '/auth/change-password'
      fullPath: '/auth/change-password'
      preLoaderRoute: typeof NoauthAuthChangePasswordIndexLazyImport
      parentRoute: typeof NoauthImport
    }
    '/_no_auth/auth/confirm-email/': {
      id: '/_no_auth/auth/confirm-email/'
      path: '/auth/confirm-email'
      fullPath: '/auth/confirm-email'
      preLoaderRoute: typeof NoauthAuthConfirmEmailIndexLazyImport
      parentRoute: typeof NoauthImport
    }
    '/_no_auth/auth/reset-password/': {
      id: '/_no_auth/auth/reset-password/'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof NoauthAuthResetPasswordIndexLazyImport
      parentRoute: typeof NoauthImport
    }
    '/_no_auth/auth/sign-in/': {
      id: '/_no_auth/auth/sign-in/'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof NoauthAuthSignInIndexLazyImport
      parentRoute: typeof NoauthImport
    }
    '/_no_auth/auth/sign-up/': {
      id: '/_no_auth/auth/sign-up/'
      path: '/auth/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof NoauthAuthSignUpIndexLazyImport
      parentRoute: typeof NoauthImport
    }
  }
}

// Create and export the route tree

interface AuthAdminRouteChildren {
  AuthAdminDepositListIdRoute: typeof AuthAdminDepositListIdRoute
  AuthAdminOrderListIdRoute: typeof AuthAdminOrderListIdRoute
  AuthAdminUserListIdRoute: typeof AuthAdminUserListIdRoute
  AuthAdminBankCardListIndexRoute: typeof AuthAdminBankCardListIndexRoute
  AuthAdminBlockedCardListIndexRoute: typeof AuthAdminBlockedCardListIndexRoute
  AuthAdminDepositListIndexRoute: typeof AuthAdminDepositListIndexRoute
  AuthAdminOrderListIndexRoute: typeof AuthAdminOrderListIndexRoute
  AuthAdminPlatipayIndexRoute: typeof AuthAdminPlatipayIndexRoute
  AuthAdminReferredUsersIndexRoute: typeof AuthAdminReferredUsersIndexRoute
  AuthAdminReportsIndexRoute: typeof AuthAdminReportsIndexRoute
  AuthAdminUserListIndexRoute: typeof AuthAdminUserListIndexRoute
  AuthAdminWalletListIndexRoute: typeof AuthAdminWalletListIndexRoute
}

const AuthAdminRouteChildren: AuthAdminRouteChildren = {
  AuthAdminDepositListIdRoute: AuthAdminDepositListIdRoute,
  AuthAdminOrderListIdRoute: AuthAdminOrderListIdRoute,
  AuthAdminUserListIdRoute: AuthAdminUserListIdRoute,
  AuthAdminBankCardListIndexRoute: AuthAdminBankCardListIndexRoute,
  AuthAdminBlockedCardListIndexRoute: AuthAdminBlockedCardListIndexRoute,
  AuthAdminDepositListIndexRoute: AuthAdminDepositListIndexRoute,
  AuthAdminOrderListIndexRoute: AuthAdminOrderListIndexRoute,
  AuthAdminPlatipayIndexRoute: AuthAdminPlatipayIndexRoute,
  AuthAdminReferredUsersIndexRoute: AuthAdminReferredUsersIndexRoute,
  AuthAdminReportsIndexRoute: AuthAdminReportsIndexRoute,
  AuthAdminUserListIndexRoute: AuthAdminUserListIndexRoute,
  AuthAdminWalletListIndexRoute: AuthAdminWalletListIndexRoute,
}

const AuthAdminRouteWithChildren = AuthAdminRoute._addFileChildren(
  AuthAdminRouteChildren,
)

interface AuthUserRouteChildren {
  AuthUserDepositInfoIdRoute: typeof AuthUserDepositInfoIdRoute
  AuthUserOrdersIdRoute: typeof AuthUserOrdersIdRoute
  AuthUserDepositInfoIndexRoute: typeof AuthUserDepositInfoIndexRoute
  AuthUserMyInformationIndexRoute: typeof AuthUserMyInformationIndexRoute
  AuthUserOrdersIndexRoute: typeof AuthUserOrdersIndexRoute
  AuthUserPartnerProgramIndexRoute: typeof AuthUserPartnerProgramIndexRoute
  AuthUserStepsIndexRoute: typeof AuthUserStepsIndexRoute
  AuthUserWalletIndexRoute: typeof AuthUserWalletIndexRoute
}

const AuthUserRouteChildren: AuthUserRouteChildren = {
  AuthUserDepositInfoIdRoute: AuthUserDepositInfoIdRoute,
  AuthUserOrdersIdRoute: AuthUserOrdersIdRoute,
  AuthUserDepositInfoIndexRoute: AuthUserDepositInfoIndexRoute,
  AuthUserMyInformationIndexRoute: AuthUserMyInformationIndexRoute,
  AuthUserOrdersIndexRoute: AuthUserOrdersIndexRoute,
  AuthUserPartnerProgramIndexRoute: AuthUserPartnerProgramIndexRoute,
  AuthUserStepsIndexRoute: AuthUserStepsIndexRoute,
  AuthUserWalletIndexRoute: AuthUserWalletIndexRoute,
}

const AuthUserRouteWithChildren = AuthUserRoute._addFileChildren(
  AuthUserRouteChildren,
)

interface AuthRouteChildren {
  AuthAdminRoute: typeof AuthAdminRouteWithChildren
  AuthUserRoute: typeof AuthUserRouteWithChildren
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAdminRoute: AuthAdminRouteWithChildren,
  AuthUserRoute: AuthUserRouteWithChildren,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface NoauthRouteChildren {
  NoauthLandingPageIndexLazyRoute: typeof NoauthLandingPageIndexLazyRoute
  NoauthAuthChangePasswordIndexLazyRoute: typeof NoauthAuthChangePasswordIndexLazyRoute
  NoauthAuthConfirmEmailIndexLazyRoute: typeof NoauthAuthConfirmEmailIndexLazyRoute
  NoauthAuthResetPasswordIndexLazyRoute: typeof NoauthAuthResetPasswordIndexLazyRoute
  NoauthAuthSignInIndexLazyRoute: typeof NoauthAuthSignInIndexLazyRoute
  NoauthAuthSignUpIndexLazyRoute: typeof NoauthAuthSignUpIndexLazyRoute
}

const NoauthRouteChildren: NoauthRouteChildren = {
  NoauthLandingPageIndexLazyRoute: NoauthLandingPageIndexLazyRoute,
  NoauthAuthChangePasswordIndexLazyRoute:
    NoauthAuthChangePasswordIndexLazyRoute,
  NoauthAuthConfirmEmailIndexLazyRoute: NoauthAuthConfirmEmailIndexLazyRoute,
  NoauthAuthResetPasswordIndexLazyRoute: NoauthAuthResetPasswordIndexLazyRoute,
  NoauthAuthSignInIndexLazyRoute: NoauthAuthSignInIndexLazyRoute,
  NoauthAuthSignUpIndexLazyRoute: NoauthAuthSignUpIndexLazyRoute,
}

const NoauthRouteWithChildren =
  NoauthRoute._addFileChildren(NoauthRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '': typeof AuthUserRouteWithChildren
  '/not_found': typeof NotfoundIndexLazyRoute
  '/landing-page': typeof NoauthLandingPageIndexLazyRoute
  '/deposit-list/$id': typeof AuthAdminDepositListIdRoute
  '/order-list/$id': typeof AuthAdminOrderListIdRoute
  '/user-list/$id': typeof AuthAdminUserListIdRoute
  '/deposit-info/$id': typeof AuthUserDepositInfoIdRoute
  '/orders/$id': typeof AuthUserOrdersIdRoute
  '/bank-card-list': typeof AuthAdminBankCardListIndexRoute
  '/blocked-card-list': typeof AuthAdminBlockedCardListIndexRoute
  '/deposit-list': typeof AuthAdminDepositListIndexRoute
  '/order-list': typeof AuthAdminOrderListIndexRoute
  '/platipay': typeof AuthAdminPlatipayIndexRoute
  '/referred-users': typeof AuthAdminReferredUsersIndexRoute
  '/reports': typeof AuthAdminReportsIndexRoute
  '/user-list': typeof AuthAdminUserListIndexRoute
  '/wallet-list': typeof AuthAdminWalletListIndexRoute
  '/deposit-info': typeof AuthUserDepositInfoIndexRoute
  '/my-information': typeof AuthUserMyInformationIndexRoute
  '/orders': typeof AuthUserOrdersIndexRoute
  '/partner-program': typeof AuthUserPartnerProgramIndexRoute
  '/steps': typeof AuthUserStepsIndexRoute
  '/wallet': typeof AuthUserWalletIndexRoute
  '/auth/change-password': typeof NoauthAuthChangePasswordIndexLazyRoute
  '/auth/confirm-email': typeof NoauthAuthConfirmEmailIndexLazyRoute
  '/auth/reset-password': typeof NoauthAuthResetPasswordIndexLazyRoute
  '/auth/sign-in': typeof NoauthAuthSignInIndexLazyRoute
  '/auth/sign-up': typeof NoauthAuthSignUpIndexLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '': typeof AuthUserRouteWithChildren
  '/not_found': typeof NotfoundIndexLazyRoute
  '/landing-page': typeof NoauthLandingPageIndexLazyRoute
  '/deposit-list/$id': typeof AuthAdminDepositListIdRoute
  '/order-list/$id': typeof AuthAdminOrderListIdRoute
  '/user-list/$id': typeof AuthAdminUserListIdRoute
  '/deposit-info/$id': typeof AuthUserDepositInfoIdRoute
  '/orders/$id': typeof AuthUserOrdersIdRoute
  '/bank-card-list': typeof AuthAdminBankCardListIndexRoute
  '/blocked-card-list': typeof AuthAdminBlockedCardListIndexRoute
  '/deposit-list': typeof AuthAdminDepositListIndexRoute
  '/order-list': typeof AuthAdminOrderListIndexRoute
  '/platipay': typeof AuthAdminPlatipayIndexRoute
  '/referred-users': typeof AuthAdminReferredUsersIndexRoute
  '/reports': typeof AuthAdminReportsIndexRoute
  '/user-list': typeof AuthAdminUserListIndexRoute
  '/wallet-list': typeof AuthAdminWalletListIndexRoute
  '/deposit-info': typeof AuthUserDepositInfoIndexRoute
  '/my-information': typeof AuthUserMyInformationIndexRoute
  '/orders': typeof AuthUserOrdersIndexRoute
  '/partner-program': typeof AuthUserPartnerProgramIndexRoute
  '/steps': typeof AuthUserStepsIndexRoute
  '/wallet': typeof AuthUserWalletIndexRoute
  '/auth/change-password': typeof NoauthAuthChangePasswordIndexLazyRoute
  '/auth/confirm-email': typeof NoauthAuthConfirmEmailIndexLazyRoute
  '/auth/reset-password': typeof NoauthAuthResetPasswordIndexLazyRoute
  '/auth/sign-in': typeof NoauthAuthSignInIndexLazyRoute
  '/auth/sign-up': typeof NoauthAuthSignUpIndexLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_no_auth': typeof NoauthRouteWithChildren
  '/_auth/_admin': typeof AuthAdminRouteWithChildren
  '/_auth/_user': typeof AuthUserRouteWithChildren
  '/not_found/': typeof NotfoundIndexLazyRoute
  '/_no_auth/landing-page/': typeof NoauthLandingPageIndexLazyRoute
  '/_auth/_admin/deposit-list/$id': typeof AuthAdminDepositListIdRoute
  '/_auth/_admin/order-list/$id': typeof AuthAdminOrderListIdRoute
  '/_auth/_admin/user-list/$id': typeof AuthAdminUserListIdRoute
  '/_auth/_user/deposit-info/$id': typeof AuthUserDepositInfoIdRoute
  '/_auth/_user/orders/$id': typeof AuthUserOrdersIdRoute
  '/_auth/_admin/bank-card-list/': typeof AuthAdminBankCardListIndexRoute
  '/_auth/_admin/blocked-card-list/': typeof AuthAdminBlockedCardListIndexRoute
  '/_auth/_admin/deposit-list/': typeof AuthAdminDepositListIndexRoute
  '/_auth/_admin/order-list/': typeof AuthAdminOrderListIndexRoute
  '/_auth/_admin/platipay/': typeof AuthAdminPlatipayIndexRoute
  '/_auth/_admin/referred-users/': typeof AuthAdminReferredUsersIndexRoute
  '/_auth/_admin/reports/': typeof AuthAdminReportsIndexRoute
  '/_auth/_admin/user-list/': typeof AuthAdminUserListIndexRoute
  '/_auth/_admin/wallet-list/': typeof AuthAdminWalletListIndexRoute
  '/_auth/_user/deposit-info/': typeof AuthUserDepositInfoIndexRoute
  '/_auth/_user/my-information/': typeof AuthUserMyInformationIndexRoute
  '/_auth/_user/orders/': typeof AuthUserOrdersIndexRoute
  '/_auth/_user/partner-program/': typeof AuthUserPartnerProgramIndexRoute
  '/_auth/_user/steps/': typeof AuthUserStepsIndexRoute
  '/_auth/_user/wallet/': typeof AuthUserWalletIndexRoute
  '/_no_auth/auth/change-password/': typeof NoauthAuthChangePasswordIndexLazyRoute
  '/_no_auth/auth/confirm-email/': typeof NoauthAuthConfirmEmailIndexLazyRoute
  '/_no_auth/auth/reset-password/': typeof NoauthAuthResetPasswordIndexLazyRoute
  '/_no_auth/auth/sign-in/': typeof NoauthAuthSignInIndexLazyRoute
  '/_no_auth/auth/sign-up/': typeof NoauthAuthSignUpIndexLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/not_found'
    | '/landing-page'
    | '/deposit-list/$id'
    | '/order-list/$id'
    | '/user-list/$id'
    | '/deposit-info/$id'
    | '/orders/$id'
    | '/bank-card-list'
    | '/blocked-card-list'
    | '/deposit-list'
    | '/order-list'
    | '/platipay'
    | '/referred-users'
    | '/reports'
    | '/user-list'
    | '/wallet-list'
    | '/deposit-info'
    | '/my-information'
    | '/orders'
    | '/partner-program'
    | '/steps'
    | '/wallet'
    | '/auth/change-password'
    | '/auth/confirm-email'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/not_found'
    | '/landing-page'
    | '/deposit-list/$id'
    | '/order-list/$id'
    | '/user-list/$id'
    | '/deposit-info/$id'
    | '/orders/$id'
    | '/bank-card-list'
    | '/blocked-card-list'
    | '/deposit-list'
    | '/order-list'
    | '/platipay'
    | '/referred-users'
    | '/reports'
    | '/user-list'
    | '/wallet-list'
    | '/deposit-info'
    | '/my-information'
    | '/orders'
    | '/partner-program'
    | '/steps'
    | '/wallet'
    | '/auth/change-password'
    | '/auth/confirm-email'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_no_auth'
    | '/_auth/_admin'
    | '/_auth/_user'
    | '/not_found/'
    | '/_no_auth/landing-page/'
    | '/_auth/_admin/deposit-list/$id'
    | '/_auth/_admin/order-list/$id'
    | '/_auth/_admin/user-list/$id'
    | '/_auth/_user/deposit-info/$id'
    | '/_auth/_user/orders/$id'
    | '/_auth/_admin/bank-card-list/'
    | '/_auth/_admin/blocked-card-list/'
    | '/_auth/_admin/deposit-list/'
    | '/_auth/_admin/order-list/'
    | '/_auth/_admin/platipay/'
    | '/_auth/_admin/referred-users/'
    | '/_auth/_admin/reports/'
    | '/_auth/_admin/user-list/'
    | '/_auth/_admin/wallet-list/'
    | '/_auth/_user/deposit-info/'
    | '/_auth/_user/my-information/'
    | '/_auth/_user/orders/'
    | '/_auth/_user/partner-program/'
    | '/_auth/_user/steps/'
    | '/_auth/_user/wallet/'
    | '/_no_auth/auth/change-password/'
    | '/_no_auth/auth/confirm-email/'
    | '/_no_auth/auth/reset-password/'
    | '/_no_auth/auth/sign-in/'
    | '/_no_auth/auth/sign-up/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  AuthRoute: typeof AuthRouteWithChildren
  NoauthRoute: typeof NoauthRouteWithChildren
  NotfoundIndexLazyRoute: typeof NotfoundIndexLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  AuthRoute: AuthRouteWithChildren,
  NoauthRoute: NoauthRouteWithChildren,
  NotfoundIndexLazyRoute: NotfoundIndexLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_auth",
        "/_no_auth",
        "/not_found/"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/_auth": {
      "filePath": "_auth.tsx",
      "children": [
        "/_auth/_admin",
        "/_auth/_user"
      ]
    },
    "/_no_auth": {
      "filePath": "_no_auth.tsx",
      "children": [
        "/_no_auth/landing-page/",
        "/_no_auth/auth/change-password/",
        "/_no_auth/auth/confirm-email/",
        "/_no_auth/auth/reset-password/",
        "/_no_auth/auth/sign-in/",
        "/_no_auth/auth/sign-up/"
      ]
    },
    "/_auth/_admin": {
      "filePath": "_auth/_admin.tsx",
      "parent": "/_auth",
      "children": [
        "/_auth/_admin/deposit-list/$id",
        "/_auth/_admin/order-list/$id",
        "/_auth/_admin/user-list/$id",
        "/_auth/_admin/bank-card-list/",
        "/_auth/_admin/blocked-card-list/",
        "/_auth/_admin/deposit-list/",
        "/_auth/_admin/order-list/",
        "/_auth/_admin/platipay/",
        "/_auth/_admin/referred-users/",
        "/_auth/_admin/reports/",
        "/_auth/_admin/user-list/",
        "/_auth/_admin/wallet-list/"
      ]
    },
    "/_auth/_user": {
      "filePath": "_auth/_user.tsx",
      "parent": "/_auth",
      "children": [
        "/_auth/_user/deposit-info/$id",
        "/_auth/_user/orders/$id",
        "/_auth/_user/deposit-info/",
        "/_auth/_user/my-information/",
        "/_auth/_user/orders/",
        "/_auth/_user/partner-program/",
        "/_auth/_user/steps/",
        "/_auth/_user/wallet/"
      ]
    },
    "/not_found/": {
      "filePath": "not_found/index.lazy.tsx"
    },
    "/_no_auth/landing-page/": {
      "filePath": "_no_auth/landing-page/index.lazy.tsx",
      "parent": "/_no_auth"
    },
    "/_auth/_admin/deposit-list/$id": {
      "filePath": "_auth/_admin/deposit-list/$id.tsx",
      "parent": "/_auth/_admin"
    },
    "/_auth/_admin/order-list/$id": {
      "filePath": "_auth/_admin/order-list/$id.tsx",
      "parent": "/_auth/_admin"
    },
    "/_auth/_admin/user-list/$id": {
      "filePath": "_auth/_admin/user-list/$id.tsx",
      "parent": "/_auth/_admin"
    },
    "/_auth/_user/deposit-info/$id": {
      "filePath": "_auth/_user/deposit-info/$id.tsx",
      "parent": "/_auth/_user"
    },
    "/_auth/_user/orders/$id": {
      "filePath": "_auth/_user/orders/$id.tsx",
      "parent": "/_auth/_user"
    },
    "/_auth/_admin/bank-card-list/": {
      "filePath": "_auth/_admin/bank-card-list/index.tsx",
      "parent": "/_auth/_admin"
    },
    "/_auth/_admin/blocked-card-list/": {
      "filePath": "_auth/_admin/blocked-card-list/index.tsx",
      "parent": "/_auth/_admin"
    },
    "/_auth/_admin/deposit-list/": {
      "filePath": "_auth/_admin/deposit-list/index.tsx",
      "parent": "/_auth/_admin"
    },
    "/_auth/_admin/order-list/": {
      "filePath": "_auth/_admin/order-list/index.tsx",
      "parent": "/_auth/_admin"
    },
    "/_auth/_admin/platipay/": {
      "filePath": "_auth/_admin/platipay/index.tsx",
      "parent": "/_auth/_admin"
    },
    "/_auth/_admin/referred-users/": {
      "filePath": "_auth/_admin/referred-users/index.tsx",
      "parent": "/_auth/_admin"
    },
    "/_auth/_admin/reports/": {
      "filePath": "_auth/_admin/reports/index.tsx",
      "parent": "/_auth/_admin"
    },
    "/_auth/_admin/user-list/": {
      "filePath": "_auth/_admin/user-list/index.tsx",
      "parent": "/_auth/_admin"
    },
    "/_auth/_admin/wallet-list/": {
      "filePath": "_auth/_admin/wallet-list/index.tsx",
      "parent": "/_auth/_admin"
    },
    "/_auth/_user/deposit-info/": {
      "filePath": "_auth/_user/deposit-info/index.tsx",
      "parent": "/_auth/_user"
    },
    "/_auth/_user/my-information/": {
      "filePath": "_auth/_user/my-information/index.tsx",
      "parent": "/_auth/_user"
    },
    "/_auth/_user/orders/": {
      "filePath": "_auth/_user/orders/index.tsx",
      "parent": "/_auth/_user"
    },
    "/_auth/_user/partner-program/": {
      "filePath": "_auth/_user/partner-program/index.tsx",
      "parent": "/_auth/_user"
    },
    "/_auth/_user/steps/": {
      "filePath": "_auth/_user/steps/index.tsx",
      "parent": "/_auth/_user"
    },
    "/_auth/_user/wallet/": {
      "filePath": "_auth/_user/wallet/index.tsx",
      "parent": "/_auth/_user"
    },
    "/_no_auth/auth/change-password/": {
      "filePath": "_no_auth/auth/change-password/index.lazy.tsx",
      "parent": "/_no_auth"
    },
    "/_no_auth/auth/confirm-email/": {
      "filePath": "_no_auth/auth/confirm-email/index.lazy.tsx",
      "parent": "/_no_auth"
    },
    "/_no_auth/auth/reset-password/": {
      "filePath": "_no_auth/auth/reset-password/index.lazy.tsx",
      "parent": "/_no_auth"
    },
    "/_no_auth/auth/sign-in/": {
      "filePath": "_no_auth/auth/sign-in/index.lazy.tsx",
      "parent": "/_no_auth"
    },
    "/_no_auth/auth/sign-up/": {
      "filePath": "_no_auth/auth/sign-up/index.lazy.tsx",
      "parent": "/_no_auth"
    }
  }
}
ROUTE_MANIFEST_END */
