/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as DashboardImport } from './routes/_dashboard'
import { Route as DashboardUserTaskListIndexImport } from './routes/_dashboard/user-task-list/index'
import { Route as DashboardUserListIndexImport } from './routes/_dashboard/user-list/index'
import { Route as DashboardTaskListIndexImport } from './routes/_dashboard/task-list/index'
import { Route as DashboardOrderListIndexImport } from './routes/_dashboard/order-list/index'
import { Route as DashboardHistoryTransactionsIndexImport } from './routes/_dashboard/history-transactions/index'
import { Route as DashboardBankInfoIndexImport } from './routes/_dashboard/bank-info/index'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()
const NotfoundIndexLazyImport = createFileRoute('/not_found/')()
const AuthSignUpIndexLazyImport = createFileRoute('/auth/sign-up/')()
const AuthSignInIndexLazyImport = createFileRoute('/auth/sign-in/')()

// Create/Update Routes

const DashboardRoute = DashboardImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const NotfoundIndexLazyRoute = NotfoundIndexLazyImport.update({
  id: '/not_found/',
  path: '/not_found/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/not_found/index.lazy').then((d) => d.Route),
)

const AuthSignUpIndexLazyRoute = AuthSignUpIndexLazyImport.update({
  id: '/auth/sign-up/',
  path: '/auth/sign-up/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/auth/sign-up/index.lazy').then((d) => d.Route),
)

const AuthSignInIndexLazyRoute = AuthSignInIndexLazyImport.update({
  id: '/auth/sign-in/',
  path: '/auth/sign-in/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/auth/sign-in/index.lazy').then((d) => d.Route),
)

const DashboardUserTaskListIndexRoute = DashboardUserTaskListIndexImport.update(
  {
    id: '/user-task-list/',
    path: '/user-task-list/',
    getParentRoute: () => DashboardRoute,
  } as any,
)

const DashboardUserListIndexRoute = DashboardUserListIndexImport.update({
  id: '/user-list/',
  path: '/user-list/',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardTaskListIndexRoute = DashboardTaskListIndexImport.update({
  id: '/task-list/',
  path: '/task-list/',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardOrderListIndexRoute = DashboardOrderListIndexImport.update({
  id: '/order-list/',
  path: '/order-list/',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardHistoryTransactionsIndexRoute =
  DashboardHistoryTransactionsIndexImport.update({
    id: '/history-transactions/',
    path: '/history-transactions/',
    getParentRoute: () => DashboardRoute,
  } as any)

const DashboardBankInfoIndexRoute = DashboardBankInfoIndexImport.update({
  id: '/bank-info/',
  path: '/bank-info/',
  getParentRoute: () => DashboardRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof DashboardImport
      parentRoute: typeof rootRoute
    }
    '/not_found/': {
      id: '/not_found/'
      path: '/not_found'
      fullPath: '/not_found'
      preLoaderRoute: typeof NotfoundIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/_dashboard/bank-info/': {
      id: '/_dashboard/bank-info/'
      path: '/bank-info'
      fullPath: '/bank-info'
      preLoaderRoute: typeof DashboardBankInfoIndexImport
      parentRoute: typeof DashboardImport
    }
    '/_dashboard/history-transactions/': {
      id: '/_dashboard/history-transactions/'
      path: '/history-transactions'
      fullPath: '/history-transactions'
      preLoaderRoute: typeof DashboardHistoryTransactionsIndexImport
      parentRoute: typeof DashboardImport
    }
    '/_dashboard/order-list/': {
      id: '/_dashboard/order-list/'
      path: '/order-list'
      fullPath: '/order-list'
      preLoaderRoute: typeof DashboardOrderListIndexImport
      parentRoute: typeof DashboardImport
    }
    '/_dashboard/task-list/': {
      id: '/_dashboard/task-list/'
      path: '/task-list'
      fullPath: '/task-list'
      preLoaderRoute: typeof DashboardTaskListIndexImport
      parentRoute: typeof DashboardImport
    }
    '/_dashboard/user-list/': {
      id: '/_dashboard/user-list/'
      path: '/user-list'
      fullPath: '/user-list'
      preLoaderRoute: typeof DashboardUserListIndexImport
      parentRoute: typeof DashboardImport
    }
    '/_dashboard/user-task-list/': {
      id: '/_dashboard/user-task-list/'
      path: '/user-task-list'
      fullPath: '/user-task-list'
      preLoaderRoute: typeof DashboardUserTaskListIndexImport
      parentRoute: typeof DashboardImport
    }
    '/auth/sign-in/': {
      id: '/auth/sign-in/'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/auth/sign-up/': {
      id: '/auth/sign-up/'
      path: '/auth/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpIndexLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

interface DashboardRouteChildren {
  DashboardBankInfoIndexRoute: typeof DashboardBankInfoIndexRoute
  DashboardHistoryTransactionsIndexRoute: typeof DashboardHistoryTransactionsIndexRoute
  DashboardOrderListIndexRoute: typeof DashboardOrderListIndexRoute
  DashboardTaskListIndexRoute: typeof DashboardTaskListIndexRoute
  DashboardUserListIndexRoute: typeof DashboardUserListIndexRoute
  DashboardUserTaskListIndexRoute: typeof DashboardUserTaskListIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardBankInfoIndexRoute: DashboardBankInfoIndexRoute,
  DashboardHistoryTransactionsIndexRoute:
    DashboardHistoryTransactionsIndexRoute,
  DashboardOrderListIndexRoute: DashboardOrderListIndexRoute,
  DashboardTaskListIndexRoute: DashboardTaskListIndexRoute,
  DashboardUserListIndexRoute: DashboardUserListIndexRoute,
  DashboardUserTaskListIndexRoute: DashboardUserTaskListIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '': typeof DashboardRouteWithChildren
  '/not_found': typeof NotfoundIndexLazyRoute
  '/bank-info': typeof DashboardBankInfoIndexRoute
  '/history-transactions': typeof DashboardHistoryTransactionsIndexRoute
  '/order-list': typeof DashboardOrderListIndexRoute
  '/task-list': typeof DashboardTaskListIndexRoute
  '/user-list': typeof DashboardUserListIndexRoute
  '/user-task-list': typeof DashboardUserTaskListIndexRoute
  '/auth/sign-in': typeof AuthSignInIndexLazyRoute
  '/auth/sign-up': typeof AuthSignUpIndexLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '': typeof DashboardRouteWithChildren
  '/not_found': typeof NotfoundIndexLazyRoute
  '/bank-info': typeof DashboardBankInfoIndexRoute
  '/history-transactions': typeof DashboardHistoryTransactionsIndexRoute
  '/order-list': typeof DashboardOrderListIndexRoute
  '/task-list': typeof DashboardTaskListIndexRoute
  '/user-list': typeof DashboardUserListIndexRoute
  '/user-task-list': typeof DashboardUserTaskListIndexRoute
  '/auth/sign-in': typeof AuthSignInIndexLazyRoute
  '/auth/sign-up': typeof AuthSignUpIndexLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/_dashboard': typeof DashboardRouteWithChildren
  '/not_found/': typeof NotfoundIndexLazyRoute
  '/_dashboard/bank-info/': typeof DashboardBankInfoIndexRoute
  '/_dashboard/history-transactions/': typeof DashboardHistoryTransactionsIndexRoute
  '/_dashboard/order-list/': typeof DashboardOrderListIndexRoute
  '/_dashboard/task-list/': typeof DashboardTaskListIndexRoute
  '/_dashboard/user-list/': typeof DashboardUserListIndexRoute
  '/_dashboard/user-task-list/': typeof DashboardUserTaskListIndexRoute
  '/auth/sign-in/': typeof AuthSignInIndexLazyRoute
  '/auth/sign-up/': typeof AuthSignUpIndexLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/not_found'
    | '/bank-info'
    | '/history-transactions'
    | '/order-list'
    | '/task-list'
    | '/user-list'
    | '/user-task-list'
    | '/auth/sign-in'
    | '/auth/sign-up'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/not_found'
    | '/bank-info'
    | '/history-transactions'
    | '/order-list'
    | '/task-list'
    | '/user-list'
    | '/user-task-list'
    | '/auth/sign-in'
    | '/auth/sign-up'
  id:
    | '__root__'
    | '/'
    | '/_dashboard'
    | '/not_found/'
    | '/_dashboard/bank-info/'
    | '/_dashboard/history-transactions/'
    | '/_dashboard/order-list/'
    | '/_dashboard/task-list/'
    | '/_dashboard/user-list/'
    | '/_dashboard/user-task-list/'
    | '/auth/sign-in/'
    | '/auth/sign-up/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  NotfoundIndexLazyRoute: typeof NotfoundIndexLazyRoute
  AuthSignInIndexLazyRoute: typeof AuthSignInIndexLazyRoute
  AuthSignUpIndexLazyRoute: typeof AuthSignUpIndexLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  DashboardRoute: DashboardRouteWithChildren,
  NotfoundIndexLazyRoute: NotfoundIndexLazyRoute,
  AuthSignInIndexLazyRoute: AuthSignInIndexLazyRoute,
  AuthSignUpIndexLazyRoute: AuthSignUpIndexLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_dashboard",
        "/not_found/",
        "/auth/sign-in/",
        "/auth/sign-up/"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/_dashboard": {
      "filePath": "_dashboard.tsx",
      "children": [
        "/_dashboard/bank-info/",
        "/_dashboard/history-transactions/",
        "/_dashboard/order-list/",
        "/_dashboard/task-list/",
        "/_dashboard/user-list/",
        "/_dashboard/user-task-list/"
      ]
    },
    "/not_found/": {
      "filePath": "not_found/index.lazy.tsx"
    },
    "/_dashboard/bank-info/": {
      "filePath": "_dashboard/bank-info/index.tsx",
      "parent": "/_dashboard"
    },
    "/_dashboard/history-transactions/": {
      "filePath": "_dashboard/history-transactions/index.tsx",
      "parent": "/_dashboard"
    },
    "/_dashboard/order-list/": {
      "filePath": "_dashboard/order-list/index.tsx",
      "parent": "/_dashboard"
    },
    "/_dashboard/task-list/": {
      "filePath": "_dashboard/task-list/index.tsx",
      "parent": "/_dashboard"
    },
    "/_dashboard/user-list/": {
      "filePath": "_dashboard/user-list/index.tsx",
      "parent": "/_dashboard"
    },
    "/_dashboard/user-task-list/": {
      "filePath": "_dashboard/user-task-list/index.tsx",
      "parent": "/_dashboard"
    },
    "/auth/sign-in/": {
      "filePath": "auth/sign-in/index.lazy.tsx"
    },
    "/auth/sign-up/": {
      "filePath": "auth/sign-up/index.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
